### ISSUE TITLE
Time variable

### ISSUE THREAD

**Issue by robsonsobral** [lukesampson/pshazz#106]
Hi! Thank you for saving me from type the hostnames on ssh_config completely.

Is it possible to add time to the cursor? Something like 16:16. I couldn't find a variable to do it.

Thank you!

**Comment by h404bi** [comment]
You can use PowerShell cmdlet to get time and add it to prompt like this:

```
    "prompt": [
        [ "darkcyan",   "", " $(Get-Date -Format 'HH:mm:ss')" ]
    ]
```

**Comment by robsonsobral** [comment]
Thank you so much, @h404bi !
