### ISSUE TITLE
Pshazz runs slow

### ISSUE THREAD

**Issue by scottwillmoore** [lukesampson/pshazz#13]
Hello, I don't know if there is anyway to improve this, but pshazz on my computer runs much slower than a native prompt. I would have expected a slight delay, however it actually takes about 3 extra seconds to start, and when entering a command, it can take around a second for a new prompt to appear, before I can start typing. It would be great if there were a way to improve some of these speed issues.

Also tab-completion on many things including files (however this may be powershell itself) is slow, and not responsive with a clear delay before the tab-completion appears.

I do not believe my current device specs would be an issue,

```
Sony Vaio Pro (Laptop)

Operating System: Windows 8.1 Pro
Processor: i7-4500U
Memory: 8GB
Storage: All SSD
```

Also have a desktop, but reluctant to install scoop on it until my next fresh install as I already have many software tools such as python and ruby installed on that machine.

Just recently started using pshazz and it is fantastic by the way, similar to oh-my-zsh. :smile:

**Comment by jdgregson** [comment]
Kind of an old issue, but I am seeing similar behavior. If I enable git in my theme and then cd to another directory, the cursor blinks twice before the prompt comes back. If I remove git and reload the theme, I can cd instantaneously.
