### ISSUE TITLE
How about manage multiple ssh keys?

### ISSUE THREAD

**Issue by nightire** [lukesampson/pshazz#14]
Suppose I have multiple ssh keys under my ~/.ssh folder, pshazz will help to manage the id_rsa by default, but what about others? Manually add them by using ssh-add?

Is there a best practice of using pshazz to manage multiple ssh keys?

**Comment by lukesampson** [comment]
I haven't tried it, but does [this answer](http://superuser.com/a/272613/35237) help?

**Comment by nightire** [comment]
Yes, this works. Actually I always use ssh config on Linux/Mac, but forgot to copy this to windows. Thanks for reminding me, closed.
