### ISSUE TITLE
Replacing ssh agent with gpg-agent

### ISSUE THREAD

**Issue by jyrkij** [lukesampson/pshazz#15]
Is there any way to replace ssh-agent with gpg-agent? I'd like to do this to get my smart card working properly for OpenSSH.

**Comment by lukesampson** [comment]
It should be possible in theory, but I don't think anyone has done this yet. You would need to create a plugin that handles the gpg-agent calls (you could use the [SSH Plugin](https://github.com/lukesampson/pshazz/blob/master/plugins/ssh.ps1) as a starting point). And then you would need to modify your Pshazz [theme](https://github.com/lukesampson/pshazz/wiki/Theme-format) to use the new plugin.

Sorry I haven't had any experience with gpg-agent, but I'd love to get a Pull Request if you can work out how to do it.
