### ISSUE TITLE
No prompt on Powershell ISE

### ISSUE THREAD

**Issue by rszuster** [lukesampson/pshazz#17]
The prompt disappears when 'pshazz init' is executed in the Powershell ISE console pane, working ok in standard Powershell Console though.

**Comment by lukesampson** [comment]
Yes, it's not designed to work in Powershell ISE.

**Comment by Kiedtl** [comment]
This is because pshazz uses `write-host`, instead of `write-prompt` or `write-output`, which doesn't work in PowerShell ISE.
Maybe somebody could submit a PR which uses `write-output` with ANSI terminal sequences to use color. Something like:
```powershell
$E = [char]27
$resetColor = "$E[0m"
$red = "$E[38;2;255;0;0m"
$blue = "$E[38;2;0;0;255m"

function prompt {
     "PS ${blue}$(pwd.Path)${red}>>>"
}
