### ISSUE TITLE
pshazz slow

### ISSUE THREAD

**Issue by mmcalli** [lukesampson/pshazz#35]
Hi

I'm having a problem when using pshazz (installed with scoop). I have just the default theme installed, and yes, do have the ssh agent running, so do expect some time for the powershell window to open.

Here's the timings I've discovered:-
- Simply pressing enter in a powershell window, no command. Takes around 4 seconds to return another prompt.
- (From windows powershell startup) "$(resolve-path $(scoop which ssh))" ... takes 14s. I can live with this one if necessary.
- $null = gcm pshazz -ea stop ... takes 9s.
- pshazz init 'default' ... takes 51s

Do you have any ideas what might be causing this? I am on Windows 10, but this problem was occurring on Windows 7 as well. To help troubleshoot, here's the scoop packages I have installed (after uninstalling pshazz):-

Installed apps:

  7zip (15.14)
  concfg (0.2016.01.25)
  coreutils (5.97.3)
  curl (7.46.0)
  git (2.7.1.windows.2)
  gow (0.8.0)
  grep (2.5.4)
  gzip (1.3.12)
  innounp (0.45)
  ln (0.2015.04.25)
  maven (3.3.9)
  openssh (5.4p1-1)
  pdftk (2.02)
  python27 (2.7.11)
  sed (4.2.1)
  ssh-copy-id (2015-03-22)
  tar (1.23)
  vim (7.4)
  wget (1.16.3)

**Comment by TobiasTimm** [comment]
Have you tested it with a theme where is no git/hg status? Most of the time the performance issues are caused by hg/git
