### ISSUE TITLE
Custom theme path

### ISSUE THREAD

**Issue by eugenesvk** [lukesampson/pshazz#37]
Is it possible to set a custom folder for my theme (not `Users\username\pshazz`)?
I've given up on the `Users\Username` exactly because way too many apps use it to place their precious junk :), so I organize my own files elsewhere and would like pshazz to be able to find it without any of the symlink abomination. Is there a variable I can set in my profile that would tell pshazz to look for a theme there?
Thank you!

**Comment by lukesampson** [comment]
To change these environment variables beyond the current powershell scope, use:
```
[environment]::setenvironmentvariable('SCOOP_CFG','c:\path\to\.pshazz','user')
[environment]::setenvironmentvariable('SCOOP_THEMES','c:\path\to\themes','user')
```

you will need to restart your powershell session, or manually set `$env:SCOOP_CFG` and $env:SCOOP_THEMES`.

**Comment by eugenesvk** [comment]
Hm, this didn't work. At first I thought it's because of having `'user'` in there since after assigning a var that way I couldn't even read it with `$env:SCOOP_THEMES`
But then I removed `'user'`, so I could read it to check if it's set (and it is), but I still get the error `pshazz: error: couldn't load theme 'es' in C:\dev\apps\pshazz\0.2016.03.24\themes`

**Comment by eugenesvk** [comment]
Ah, found it — there is a typo, it should be `PSHAZZ_THEMES` instead of `SCOOP_THEMES`

**Comment by eugenesvk** [comment]
Thanks, it's working now!
