### ISSUE TITLE
Add other plugin variable

### ISSUE THREAD

**Issue by silvinus** [lukesampson/pshazz#45]
Hi,

Is it possible to add more plugin vars for git ? The perfect goal is to have a prompt like posh-git that can display more information about repo modification.

You can see prompt of posh-git here https://github.com/dahlbyk/posh-git.

It can be displayed modified files, added/deleted...

Thank's for your help

**Comment by lukesampson** [comment]
I'd be happy to accept a pull request to add more variables. I find that much git information in the prompt overwhelming, so I probably won't get around to this myself ;)
