### ISSUE TITLE
Documentation for themes

### ISSUE THREAD

**Issue by TobiasTimm** [lukesampson/pshazz#55]
Is there any documentation how a theme is structured and what Vars are available?

I don't know the parameters for an entry in the `prompt` section:
```
  "prompt": [
   [ "cyan",  "", "$path" ],
   [ "red",   "", "$git_lbracket$git_branch$git_dirty$git_rbracket" ],
   [ "red",   "", "$hg_lbracket$hg_branch$hg_bookmark$hg_dirty$hg_rbracket" ],
   [ "green", "", "`n$([char]0x3BB)$([char]0x0BB)" ]
   ],
```

**Comment by lukesampson** [comment]
Sorry, there isn't really any documentation. The theme file defines plugins and prompt, and then each plugin can read further settings from the theme file.

Each sub array in `"prompt"` is `[ "foreground-color", "background-color", "string to output" ]`. These get written out sequentially.

The common variables like `$path` are [here](https://github.com/lukesampson/pshazz/blob/master/lib/prompt.ps1#L104), and plugins can add their own prompt variables in the `global:pshazz:[plugin-name]:prompt` function, e.g. for [git](https://github.com/lukesampson/pshazz/blob/master/plugins/git.ps1#L88) you can see the var names added, and you can see how some of these can be overridden in the theme JSON [here](https://github.com/lukesampson/pshazz/blob/master/plugins/git.ps1#L4).

**Comment by lukesampson** [comment]
The wiki page [here](https://github.com/lukesampson/pshazz/wiki/Theme-format) might be of help.

**Comment by TobiasTimm** [comment]
Ah thx 👍 I've missed this wiki page completly
