### ISSUE TITLE
No any dialogs popup for getting passphase, git push still keep asking for passphase

### ISSUE THREAD

**Issue by jeud** [lukesampson/pshazz#59]
Dear all

I have successfully installed `pshazz` using `scoop install pshazz`

I try to use `git push -u origin master` to push to my repository, no dialogs shown up, so I manually using `ssh-add` to add Key into `ssh-agent`

```
ssh-add c:/Users/username/.ssh/xxx_id_rsa
# i have entered passphase at this prompt

ssh-add -l
# i got confirmation that Key has been added
```

The next `git push` still keep asking me for the passphase

![](http://i.cubeupload.com/OwH1m1.png)

Please guide, what did I do wrong
Thanks

**Comment by h404bi** [comment]
#76  New ssh plugin should be able to handle key passphrase better.

**Comment by pierremtb** [comment]
Same here, just no popup when installing pshazz, and git keeps on asking for my passphrase. Any idea?
My setup is `git-with-openssh` and `pshazz`, on a W10 machine.
