### ISSUE TITLE
Needing to run 'pshazz init' every time I open PowerShell

### ISSUE THREAD

**Issue by YajJackson** [lukesampson/pshazz#64]
For the longest time pshazz was automatically running with I would open PowerShell, and for some reason I'm needing to do as the title suggests to have it run.

**Comment by arthurcohen** [comment]
Please, check your powershell profile. 

In your file must have something like this:* 
`try { $null = gcm pshazz -ea stop; pshazz init } catch { }`

If not, yout have 2 options:
1. Reinstall pshazz
2. Insert this* piece of code manually

**Comment by YajJackson** [comment]
@arthurcohen Thanks a ton, reinstalling solved the problem! (Why didn't I try turning it off and back on the first time?)
