### ISSUE TITLE
askpass version outdated

### ISSUE THREAD

**Issue by noquierouser** [lukesampson/pshazz#72]
This might be a duplicate of #70, #24 and other issues, but it seems that the version of `askpass.exe` in this repo is outdated. The README refers to git-credential-winstore which is no longer developed as such and now is [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) by Microsoft.

In that repo I see references to `cli-askpass` which might be useful for this project because [the ArgumentNullException error has been fixed there](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/518).

**Comment by noquierouser** [comment]
I tried downloading the latest release of GCM from the mentioned repo and replaced pshazz's `askpass.exe` with the `git-askpass.exe` from GCM, to no avail. Probably GCM's `git-askpass.exe` is fundamentally different from pshazz's `askpass.exe`, so maybe I'm wrong.

**Comment by TCB13** [comment]
pshazz seems to be fundamentally broken and nobody cares :(

**Comment by h404bi** [comment]
FYI: pshazz uses an askpass which different from GCM, https://github.com/lukesampson/askpass.

**Comment by h404bi** [comment]
askpass has been removed in #76 , closed.
