### ISSUE TITLE
Pshazz SSH agent does not work

### ISSUE THREAD

**Issue by t0mmetje** [lukesampson/pshazz#84]
I followed the steps in https://github.com/lukesampson/scoop/wiki/SSH-on-Windows but it doesn't work for me. I have the following apps installed (I also tried with `openssh` instead of `git-with-openssh`).

```
PS C:\Users\marcoent\Documents> scoop list
Installed apps:

  7zip 18.06
  coreutils 5.97.3 {32bit}
  curl 7.63.0
  dd 0.6beta3
  gcc 8.1.0 {32bit}
  git 2.20.1.windows.1
  git-with-openssh 2.20.1.windows.1
  grep 2.5.4
  mc 4.8.19 [extras]
  neovim 0.3.3
  openssh 7.6p1
  pshazz 0.2019.02.04
  sed 4.2.1
```

When I SSH into a server with `ssh username@example.org` I am asked for the password of my private key and after entering it, I'm logged into the server. Excellent! However, once I log out and want to log back in, I have to enter the password of my private key again.

```
PS C:\Users\marcoent\Documents> ssh-add -l
Could not open a connection to your authentication agent.
```

So I expect the tutorial is missing some crucial bits between installing `pshazz` and everything magically working.

**Comment by t0mmetje** [comment]
My `$profile` contained: `try { $null = gcm pshazz -ea stop; pshazz init 'default' } catch { }`. After changing the theme to something and back to the default, I got asked to enter my private key password. After entering it once, I was able to SSH into my server multiple times without entering the password.

**Comment by Yunuuuu** [comment]
The same problem in the latest `pshazz` installed by `scoop` in win11

**Comment by Yunuuuu** [comment]
Although following these steps, it remain fail to work.
> My `$profile` contained: `try { $null = gcm pshazz -ea stop; pshazz init 'default' } catch { }`. After changing the theme to something and back to the default, I got asked to enter my private key password. After entering it once, I was able to SSH into my server multiple times without entering the password.

**Comment by tolache** [comment]
>My $profile contained: try { $null = gcm pshazz -ea stop; pshazz init 'default' } catch { }. After changing the theme to something and back to the default, I got asked to enter my private key password. After entering it once, I was able to SSH into my server multiple times without entering the password.

@tommarcoen, could you clarify what you mean by "changing the theme"?

**Comment by tommarcoen** [comment]
I changed jobs since three years ago and I haven't been using this software since so I am not sure what I meant or what I did in detail. I will try to install the software again and go through the steps once more to provide more details, should the issue manifest itself again.
