### ISSUE TITLE
The color of integrated VSCode terminal is broken now

### ISSUE THREAD

**Issue by guikarist** [lukesampson/pshazz#92]
After installing pshazz, this issue occurs. I have tried reinstalling VSCode and uninstalling pshazz, but nothing changed.
![image](https://user-images.githubusercontent.com/19543014/54930931-1d105400-4f53-11e9-890b-6beb10b988b7.png)

**Comment by h404bi** [comment]
weird, pshazz won't change command colors, have you installed concfg?

**Comment by guikarist** [comment]
Yes. But I have done these two:

```
concfg import powershell-default
concfg import basic-reset
```

And there is [someone who also encounters this](https://github.com/PowerShell/vscode-powershell/issues/792#issuecomment-343173860).

**Comment by guikarist** [comment]
Unfortunately I bought a new computer, which made this issue hard to reproduce.

**Comment by firede** [comment]
![image](https://user-images.githubusercontent.com/157338/59778083-653bda00-92e8-11e9-9958-cf9c1944f5cd.png)

I have encountered the same issue, even though I deleted pshazz and concfg.
