### ISSUE TITLE
Exception thrown when changing themes

### ISSUE THREAD

**Issue by maxshaffer** [lukesampson/pshazz#93]
I have a fresh install of pshazz and scoop on Windows 10. When I try to change themes, I get an error.

system32 $ pshazz use aag
Exception setting "theme": "The property 'theme' cannot be found on this object. Verify that the property exists and can be set."
At C:\Users\max\scoop\apps\pshazz\current\lib\config.ps1:26 char:9
         $cfg.$name = $val
         ~~~~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
 FullyQualifiedErrorId : ExceptionWhenSetting

**Comment by h404bi** [comment]
Should be fixed in https://github.com/lukesampson/pshazz/commit/8a23d403af1ac9dd5f7755752bbf52a1cea9d257 , please update pshazz to the latest version later on.

**Comment by maxshaffer** [comment]
I'm running 0.2019.03.23. Scoop says this is the latest...
$ scoop update pshazz
pshazz: 0.2019.03.23 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'

**Comment by h404bi** [comment]
The manifests update automation is in schedule, please wait for it to be executed. It will take some time.
